### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by wonseop-lee** [wonseop-lee/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a background
- [x] Add a car
- [x] Verify that a user can see the car at the top left corner
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all bugs.
