### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by wonseop-lee** [wonseop-lee/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data model that indicates which way the car is facing.
- [x] Listen for `keydown` events on the `document` to turn the car.
- [x] Update the data model when an arrow key is pressed.
- [x] Update the car's direction according to the data model.
- [x] Add transition when the car turns.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again.
- [ ] Fix all bugs.
